<?php

define('DEFAULT_CURRENCY', 'EUR');
define('DATE_FORMAT', 'Y-m-d');

define('MAXIMUM_CASH_IN_COMMISSION_AMOUNT', 500);
define('MINIMUM_CASH_OUT_COMMISSION_AMOUNT', 50);

define('OPERATION_CASH_OUT_COMMISSION_PERCENTAGE', 0.3);
define('OPERATION_CASH_IN_COMMISSION_PERCENTAGE', 0.03);

define('WEEKLY_OPERATION_LIMIT_FOR_DISCOUNT', 3);

   